### PR TITLE
James-jdkim remove unused log4j

### PR DESCRIPTION
**Pull request by quantranhong1999**
As discussed here: https://github.com/linagora/james-project/issues/4453

We should switch to slf4j instead of depending on a logging library implementation like log4j.

The weird thing is I do not need any refactoring following this change. James JDKIM likely does not use any logging since then?

### CODE REVIEW

**Comment by chibenwa** [comment]
Likely not. Then we can remove the logger dependencies IMO.

Also there seems like there is a compilation error...

**Comment by Arsnael** [comment]
```
mvn -U -B -e clean install -DskipTests -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS

/home/jenkins/tools/maven/latest3//bin/mvn: 194: exec: /home/jenkins/tools/java/latest11/bin/java: Exec format error
```
Odd... Might want to try that on local

**Comment by quantranhong1999** [comment]
> ```
> mvn -U -B -e clean install -DskipTests -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS
> 
> /home/jenkins/tools/maven/latest3//bin/mvn: 194: exec: /home/jenkins/tools/java/latest11/bin/java: Exec format error
> ```
> 
> Odd... Might want to try that on local

Why CI have this params in its build command: `-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS` ?

I did not try these params on my local TBH.

**Comment by ieugen** [comment]
Exec format - might mean a different CPU architecture  https://mkyong.com/java/bash-usr-bin-java-cannot-execute-binary-file-exec-format-error/

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/INFRA-22620?jql=project%20%3D%20INFRA%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20created%20DESC%2C%20priority%20DESC%2C%20updated%20DESC

```
This must be caused by https://github.com/apache/infrastructure-p6/pull/912
It looks like the ARM64 .deb has been installed instead of the AMD64 one. 
```

**Review by chibenwa — APPROVED** [review]

File: main/pom.xml [hunk 1]
```diff
@@ -60,9 +60,8 @@
             <artifactId>apache-mime4j-dom</artifactId>
         </dependency>
         <dependency>
-            <groupId>org.apache.logging.log4j</groupId>
-            <artifactId>log4j-core</artifactId>
-            <scope>runtime</scope>
+            <groupId>org.slf4j</groupId>
+            <artifactId>slf4j-api</artifactId>
```
Comment (chibenwa) [inline main/pom.xml:64]: Do we need SLF4J at all or we can remove it too?

**Review by Arsnael — APPROVED** [review]

File: main/pom.xml (hunk 1 above)
Comment (quantranhong1999) [reply main/pom.xml]: Let remove it then.

**Review by Arsnael — APPROVED** [review]
